name = "thanaweya"
main = "worker/index.ts"
compatibility_date = "2026-09-22"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "thanaweya-db"
migrations_dir = "./migrations"
